name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'The name of the app which you are deploying, e.g. "hello-bosun". Leave empty to autodetect from the repo/runner.'
        required: false
      image-tag:
        description: 'The short image tag to deploy (just the bit after the ":" in the container image URL).'
        required: true
      config-ref:
        description: 'The git ref (branch, tag or full length SHA) at which to obtain the bosun.yaml config to apply. For a full roll-back this should probably align with the image tag.'
        required: true
        default: main
      environment:
        description: 'The environment to which the app will be deployed'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
      clusters:
        description: 'list of clusters to deploy i.e "cluster-01,cluster-02"'
        required: true
        default: 'cluster-01,cluster-02'
        type: choice
        options:
          - cluster-01
          - cluster-02
          - cluster-01,cluster-02
      deploy-suffix:
        description: 'Sub environment to be deployed, if no suffix "" is provided, it will deploy to main environment.'
        default: ''
        required: false
jobs:
  deploy:
    # For more info on runner types, see https://bosun-docs-user.ext.prd.jspaas.uk/docs/build-deploy/configure-runners/
    runs-on: Ubuntu-latest
    steps:
      # This checks out the required branch of your repo
      - uses: actions/checkout@v4
